sudo: required
services:
    - docker

bundler_args: 
    --retry 5

before_install:
    - docker build -t charlytron/docker-react -f Dockerfile.dev .

script:
    - docker run charlytron/docker-react npm run test -- --coverage